### ISSUE TITLE
Criar classes básicas

### ISSUE THREAD

**Issue by johnnysaymon** [ciebit/persons#1]
Criar a classe abstrata `Person` e as classes concretas `Natural` e `Legal`.

Segue UML. Favor desconsiderar, nesse primeiro momento, os métodos e classes que irão trabalhar com as características físicas na classe `Natural`.

![person](https://user-images.githubusercontent.com/5160587/48201694-a24af180-e341-11e8-8c6e-d37e02786c99.jpg)

**Comment by johnnysaymon** [comment]
Favor notar que optei por resumir a UML não inserindo as classes `get`. Mas todos os que tem um `set` terão o respectivo meio de obtenção do dado.

**Comment by maikenegreiros** [comment]
@johnnysaymon , estive pensando em criar uma única `Collection`, que aceitaria objetos do tipo `Person`, mas numa única `Collection` iria ser possível ter `LegalPerson` e `NaturalPerson`. Isso é um problema?

**Comment by johnnysaymon** [comment]
Nenhum problema @maikenegreiros . Acredito inclusive que será bem melhor dessa forma.

**Comment by johnnysaymon** [comment]
Resolvido conforme o pull request #3
